### PR TITLE
Added Validations to registration

### PR DESCRIPTION
**Pull request by leixdd**
1. Added Validations to registration
2. Added Error Messages

### CODE REVIEW

**Review by nubiv — APPROVED** [review]

**Comment by nubiv** [comment]
Hi @leixdd Love the way you implemented the custom validations 😃. I noticed a small typo and took care of it while also linting the code. Please look at the changes and let me know if everything looks good. If so, feel free to merge this pr at your convenience!

**Comment by ha-anna** [comment]
I have a curious question btw, why do we keep mDB in src/app.ts when it's not used anywhere? Is it for future use? 🤔 I'm still kind of a young Node.js coder so I was wondering if it's something that I will keep seeing and why is it this way.

**Comment by nubiv** [comment]
> I have a curious question btw, why do we keep mDB in src/app.ts when it's not used anywhere? Is it for future use? 🤔 I'm still kind of a young Node.js coder so I was wondering if it's something that I will keep seeing and why is it this way.

Hi Anna, that's used to initialise DB connection. Since Lei exports DB.connect().useDb(dbName) directly from db.ts, it might seem to be a bit wired to you. To give you a clearer picture, imagine if we were export DB class from db.ts, and then call DB.connect().useDb(dbName) in app.ts, which is the approach I would normally do 😄

**Comment by ha-anna** [comment]
Thanks a lot @nubiv, now I get it 😆

**Review by nubiv — APPROVED** [review]

**Pull request merged**
